spring.application.name=RagProject

spring.ai.ollama.base-url= http://localhost:11434
spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.embedding.model=nomic-embed-text

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=rag-docs
spring.ai.vectorstore.qdrant.initialize-schema=true

#spring.ai.vectorstore.chroma.host=localhost
#spring.ai.vectorstore.chroma.port=8000
#spring.ai.vectorstore.chroma.collection-name=rag-docs
#spring.ai.vectorstore.chroma.initialize-schema=true
